#!/bin/sh

export ROOTSYS=/opt/root
export PATH=$ROOTSYS/bin:$PATH
rootcint -f Dictionary.cxx -c NGammaEvent.h LinkDef.h
g++ -O0 -g `root-config --cflags` analysisUCNb.cxx Dictionary.cxx -o analysisUCNb `root-config --libs` 
g++ `root-config --cflags` `root-config --libs` spectrum_analyser.cc Dictionary.cxx -o spectrum_analyser
g++ `root-config --cflags` `root-config --libs` Ge_analyser.cc Dictionary.cxx -o Ge_analyser
g++ `root-config --cflags` `root-config --libs` periodic_analyser.cc Dictionary.cxx -o periodic_analyser
#g++ `root-config --cflags` `root-config --libs` display.cxx Dictionary.cxx -o waveform_analyser
git add *.cc *.hh *.h *.cxx
