/********************************************************************
* NGammaEventDictionary.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error NGammaEventDictionary.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableNGammaEventDictionary();
extern void G__cpp_setup_inheritanceNGammaEventDictionary();
extern void G__cpp_setup_typetableNGammaEventDictionary();
extern void G__cpp_setup_memvarNGammaEventDictionary();
extern void G__cpp_setup_globalNGammaEventDictionary();
extern void G__cpp_setup_memfuncNGammaEventDictionary();
extern void G__cpp_setup_funcNGammaEventDictionary();
extern void G__set_cpp_environmentNGammaEventDictionary();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "NGammaEvent.h"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__NGammaEventDictionaryLN_TClass;
extern G__linked_taginfo G__NGammaEventDictionaryLN_TBuffer;
extern G__linked_taginfo G__NGammaEventDictionaryLN_TMemberInspector;
extern G__linked_taginfo G__NGammaEventDictionaryLN_NGammaEvent;

/* STUB derived class for protected member access */
